apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-backend
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    tier: backend
    {{- include "common.selectorLabels" . | nindent 4 }}
